### ISSUE TITLE
Levels, Sources and Destinations is not defined when initiating the Probel object

### ISSUE THREAD

**Issue by daniel-j-davis** [ryanmccartney/probel-swp-08#1]
I'm connecting to a Ross Ultrix as per the below:

```
const ULTRIX_ROUTER_IP = 'ip here';
const ULTRIX_ROUTER_PORT = 8910;

const sourceTotal = 1024;
const destinationTotal = 1024;
const levelTotal = 17;

const probel = new Probel(ULTRIX_ROUTER_IP, ULTRIX_ROUTER_PORT, sourceTotal, destinationTotal, levelTotal);
```

And I'm getting a reference error for levels, sources and destinations not being defined. I had a quick look at the code and looks like it's `levels`, `sources` and `destinations` versus `this.levels`, `this.sources` and `this.destinations`.

**Comment by ryanmccartney** [comment]
This has been fixed in v0.0.13. Config object was introduced the other day and I never properly defined the levels
